### ISSUE TITLE
[Add/update member]

### ISSUE THREAD

**Issue by AylinErma** [McGill-NLP/mcgill-nlp.github.io#186]
### Action

Add member

### Name

Aylin Erman

### Role

Master

### Status

Current Member

### Avatar

https://imgur.com/7RGjoZL.jpeg

### Advisor

Jackie Cheung

### Date

Fall 2022

### Bio

Works at the intersection of Health and AI

### Note

Co-advised by Dan Poenaru from paediatric surgery

### Website

https://aylinerma.github.io

**Comment by xhluca** [comment]
Duplicate

**Comment by xhluca** [comment]
Oops wrong one. Updating now.
