### ISSUE TITLE
update publication

### ISSUE THREAD

**Issue by arkilpatel** [McGill-NLP/mcgill-nlp.github.io#324]
### Action

Update publication

### Title

Evaluating In-Context Learning of Libraries for Code Generation

### Shorthand

icl-libraries

### Author

Arkil Patel

### Names

Arkil Patel, Siva Reddy, Dzmitry Bahdanau, Pradeep Dasigi

### Venue

NAACL

### Link

https://arxiv.org/abs/2311.09635

### Year

2024

### Month

06

### Day

17

### Tags

LLMs, in-context learning, evaluation, code generation

### Code

https://github.com/McGill-NLP/incontext-code-generation

**Comment by xhluca** [comment]
Did not work: https://github.com/McGill-NLP/mcgill-nlp.github.io/actions/runs/9023682727

can you update the markdown manually?

**Comment by xhluca** [comment]
you just need to change the front matter. all papers are here: https://github.com/McGill-NLP/mcgill-nlp.github.io/tree/main/_posts/papers (you can find yours by looking up your url)

**Comment by xhluca** [comment]
Manually done
