### ISSUE TITLE
[Add/update member] Update Benno's profile

### ISSUE THREAD

**Issue by BennoKrojer** [McGill-NLP/mcgill-nlp.github.io#35]
### Action

Update member

### Name

Benno Krojer

### Role

PhD

### Status

Current Member

### Advisor

Siva Reddy

### Date

Summer 2021

### Bio

I work on language grounding and like Ultimate Frisbee

### GitHub

https://github.com/BennoKrojer/

### Twitter

https://twitter.com/benno_krojer

### Scholar

https://scholar.google.com/citations?user=D5eyaLwAAAAJ&hl=en

### Website

https://www.bennokrojer.com/

**Comment by BennoKrojer** [comment]
Me

**Comment by xhlulu** [comment]
@BennoKrojer sorry, the instructions were unclear, but bio is supposed to be short, like 1 sentence.

For example, "Just some cool student":

![](https://github.com/McGill-NLP/mcgill-nlp.github.io/raw/main/.github/images/demo-profile.jpg)

Otherwise it'll overflow.

**Comment by xhlulu** [comment]
https://github.com/McGill-NLP/mcgill-nlp.github.io#create-a-profile-page
