### ISSUE TITLE
[Add/update member]

### ISSUE THREAD

**Issue by AdaDTur** [McGill-NLP/mcgill-nlp.github.io#355]
### Action

Add member

### Name

Ada Tur

### Role

Undergraduate

### Status

Current Member

### Username

ada.tur

### Semantic Scholar ID

2129070227

### Advisor

Siva Reddy

### Date

Summer 2024

### Bio

Working on linguistic theory advised by LLMs, and AI safety in digital web agents

### GitHub

https://github.com/AdaDTur

### Twitter

https://twitter.com/adadtur

### Scholar

https://scholar.google.com/citations?user=9td9V50AAAAJ&hl=en&authuser=1

### Website

https://adadtur.github.io/

**Comment by cesare-spinoso** [comment]
@xhluca This is causing https://github.com/McGill-NLP/mcgill-nlp.github.io/actions/runs/10010614515
