### ISSUE TITLE
Improve Google SEO, author and article metadata

### ISSUE THREAD

**Issue by AndreasMadsen** [McGill-NLP/mcgill-nlp.github.io#372]
Would be cool to have profile pages with this kind of metadata and 
* https://developers.google.com/search/docs/appearance/structured-data/profile-page

And link it with the paper pages using:
* https://developers.google.com/search/docs/appearance/structured-data/article

I can see there is already some metadata. However, I think it's incorrect. For example the authors are currently structured as:
```
<meta itemprop="description" content="Andreas Madsen, Sarath Chandar, Siva Reddy">
```

it's also listed as a `CreativeWork` which I don't think google supports. It should properly just be `Article`.

I think you can setup Google Search Console https://search.google.com/search-console/about to better inspect what google sees.

**Comment by xhluca** [comment]
Good idea! Do you know where we could we start (in terms of changing the jekyll template)?

**Comment by AndreasMadsen** [comment]
For papers:
1. Restructure authors to be a list of strings instead of a string, e.g.: https://github.com/McGill-NLP/mcgill-nlp.github.io/blob/87da2660d831e2174a8656d77f19026a8c836a59/_posts/papers/2024-07-21-2310.07819.md?plain=1#L4
2. I can't find the Jekyll template for papers, but use https://developers.google.com/search/docs/appearance/structured-data/article and refer to authors by a given ID

For authors:
_This is complicated because of the customizability_ 
1. Maybe complete https://github.com/McGill-NLP/mcgill-nlp.github.io/issues/330
2. Use https://developers.google.com/search/docs/appearance/structured-data/profile-page

**Comment by AndreasMadsen** [comment]
https://developers.google.com/search/docs/appearance/structured-data/organization is properly also a good idea. Could start with that, since it's simple.

**Comment by xhluca** [comment]
Thank you. This is a very good idea. Would you have the bandwidth to create a PR for this? @cesare-spinoso and I would be happy to review it.

**Comment by AndreasMadsen** [comment]
I already tried to look at it. However, I don't understand how the generation actually flows. For example, I cannot understand where `
<meta itemprop="description" content="Andreas Madsen, Sarath Chandar, Siva Reddy">` comes from. So I don't think I will be implementing this now.

**Comment by xhluca** [comment]
Could it be this? https://github.com/mmistakes/minimal-mistakes/blob/6be43f77a50598643e092117b50c0ea72ad9c94a/_layouts/single.html#L26

**Comment by AndreasMadsen** [comment]
Yes, that looks like it. To set it up correctly with authors, etc., I would have to mess with that setup. I don't want to start that.

I will try to setup something similar on https://chandar-lab.github.io, then you can look at that if you are interested. But we don't keep as much information there, e.g. article abstracts.

**Comment by xhluca** [comment]
Awesome!

**Comment by AndreasMadsen** [comment]
Okay, I added support for the following features to the http://chandar-lab.github.io website.
* https://developers.google.com/search/docs/appearance/structured-data/profile-page
* https://developers.google.com/search/docs/appearance/structured-data/article
* https://developers.google.com/search/docs/appearance/structured-data/organization 
* https://developers.google.com/search/docs/appearance/structured-data/breadcrumb

It takes a while for [Google Search Console](https://search.google.com/search-console/about) to index it. However, the https://search.google.com/test/rich-results validates that it works, and some profile pages are showing up now on the Search Console. 

You can look at for example https://search.google.com/test/rich-results/result?id=qLowVKOM6nA_5vg0aupGSQ. The Validator is pretty good to understand how it is structured. You can click on each property and see where in the HTML it is defined.

**Comment by xhluca** [comment]
Thanks for doing the initial work! I'm pretty busy for the next few weeks, so won't have chance to look into this. However after that i'm happy to take a stab.

@cesare-spinoso are you interested in helping out on this?

**Comment by xhluca** [comment]
this has been added in #399
