### ISSUE TITLE
[Add/update publication] Fix VinePPO's year

### ISSUE THREAD

**Issue by kazemnejad** [McGill-NLP/mcgill-nlp.github.io#376]
### Action

Update publication

### Title

VinePPO: Unlocking RL Potential For LLM Reasoning Through Refined Credit Assignment

### Shorthand

vineppo

### Author

Amirhossein Kazemnejad

### Names

Amirhossein Kazemnejad, Milad Aghajohari, Eva Portelance, Alessandro Sordoni, Siva Reddy, Aaron Courville, Nicolas Le Roux

### Venue

ArXiv

### Link

https://arxiv.org/abs/2410.01679

### Year

2024

### Month

10

### Day

02

**Comment by xhluca** [comment]
Not sure why it didn't trigger PR. could you update manually in the markdwon file and make a PR?
