### ISSUE TITLE
[update member]

### ISSUE THREAD

**Issue by dadelani** [McGill-NLP/mcgill-nlp.github.io#426]
### Action

Update member

### Name

David Ifeoluwa Adelani

### Role

Faculty

### Status

Current Member

### Username

david.adelani

### Semantic Scholar ID

2518906

### Scholar

https://scholar.google.ca/citations?user=W9sTkS0AAAAJ&hl=en

**Comment by xhluca** [comment]
I updated manually in 28fdb1f0e1a1d7ea5270aba35ed4918649274cad due to errors
