### ISSUE TITLE
[Add/update member]

### ISSUE THREAD

**Issue by ducdauge** [McGill-NLP/mcgill-nlp.github.io#50]
### Action

Add member

### Name

Edoardo M. Ponti

### Role

Postdoc

### Status

Current Member

### Avatar

https://ducdauge.github.io/authors/emponti/avatar_hu29f6bdbe94019ad2330d7a017a5d7d57_79765_250x250_fill_q90_lanczos_center.JPG

### Date

Jan 2021

### GitHub

https://github.com/ducdauge

### Twitter

https://twitter.com/PontiEdoardo

### Scholar

https://scholar.google.com/citations?user=tklL2q0AAAAJ

### Website

https://ducdauge.github.io/

**Comment by xhlulu** [comment]
✌️
