### ISSUE TITLE
[Add/update member] Vaibhav Adlakha

### ISSUE THREAD

**Issue by vaibhavad** [McGill-NLP/mcgill-nlp.github.io#61]
### Action

Add member

### Name

Vaibhav Adlakha

### Role

PhD

### Status

Current Member

### Semantic Scholar ID

1666183192

### Avatar

https://i.imgur.com/ljfeq4I.png

### Advisor

Siva Reddy

### Date

Fall 2020

### Bio

Interested in knowledge-grounded conversations

### GitHub

https://github.com/vaibhavad

### Twitter

https://twitter.com/vaibhav_adlakha

### Scholar

https://scholar.google.com/citations?user=0qmIfUoAAAAJ

**Comment by xhlulu** [comment]
I corrected the imgur link since i needed a directly link to an image.
