### ISSUE TITLE
[Add publications by an author]  Timothy J. O'Donnell

### ISSUE THREAD

**Issue by language-learning-laboratory** [McGill-NLP/mcgill-nlp.github.io#85]
### Start

2001

### End

2022

### Author ID

1400877758

**Comment by xhlulu** [comment]
There's some issues with the automation. Fixing it right now.

**Comment by xhlulu** [comment]
@language-learning-laboratory Thank you for adding those papers! 

The list of papers that were created can be seen here: https://github.com/McGill-NLP/mcgill-nlp.github.io/pull/86/files

Feel free to remove any paper that does not look right by directly editing the PR (or let me know which ones and i'll remove them). If everything's good I'll go ahead and merge it.

**Comment by xhlulu** [comment]
@language-learning-laboratory Thank you for adding those papers! 

The list of papers that were created can be seen here: https://github.com/McGill-NLP/mcgill-nlp.github.io/pull/86/files

Feel free to remove any paper that does not look right by directly editing the PR (or let me know which ones and i'll remove them). If everything's good I'll go ahead and merge it.
